apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: goapi-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: goapi-dev
      app.kubernetes.io/name: go-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
    - default
